apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping-service
          image: ghcr.io/jaygung17/shipping-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: AMQP_URL
              #set as amqp://<username>:<password>@rabbitmq:5672, 
              value: "amqp://jaygung17:jaygung17password@rabbitmq.default.svc.cluster.local:5672"
